### ISSUE TITLE
【发票】应付合同的发票新建功能无法使用

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#100]
### Description

测试问题：
应付合同的发票新建功能无法使用。新建时必填项“费用类别”为空，也无法手动建

### Steps To Reproduce 重现步骤

操作步骤：
应付-》应付合同-》相关-》发票-》新建
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/6cf428d8-a5be-4f86-927c-5734ef65b231)

### Version 版本

2.6.3

**Comment by lizheng-steedos** [comment]
关联任务：
-  #94
