### ISSUE TITLE
[新建合同]: 新建应付/应收合同时的经办人和经办部门自动带出

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#107]
### Description

新建应付合同时的经办人和经办部门自动带出

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/1eb3f9f2-a6e6-4372-864c-54becd6b394d)

### Version 版本

2.3.6

**Comment by lizheng-steedos** [comment]
经办人已经调整
