### ISSUE TITLE
[Task]: 付款单对象调整

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos-labs/feikongwang#116]
### SubTasks 子任务

- [x] 付款单增加状态：待支付、已支付；
- [x] 付款单子表明细单做；
- [ ] 付款单支付后根据付款明细自动生成对应合同的付款记录；
- [x] 付款明细中的发票对象删掉；

**Comment by marchtian** [comment]
付款单支付后根据付款明细自动生成对应合同的付款记录 
拆分为单独的issue ： https://github.com/steedos-labs/feikongwang/issues/129
