### ISSUE TITLE
【审批】待审批流程不会在审批列表中出现，当有待审批的流程时只九宫格上有红点显示

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#122]
### Description

测试问题：
待审批流程不会在审批列表中出现，当有待审批的流程时只九宫格上有红点显示

预期结果：
待审批流程可以在审批台账中显示

### Steps To Reproduce 重现步骤

操作步骤：
应付-》应付合同-》新建-》发起审批-》流程走到下一步-》下一步负责人查看

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/e339e958-8f66-4052-b0ce-099e3685a535)

### Version 版本

2.6.3

**Comment by lizheng-steedos** [comment]
后台流程、流程分类删除，重启服务后再发起流程尝试
