### ISSUE TITLE
【审批】发起应付合同审批，流程界面不会显示合同所关联的相关信息，目前只关联上了金额

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#123]
### Description

测试问题：
发起应付合同审批，流程界面不会显示合同所关联的相关信息，目前只关联上了金额

预期结果：
自动填满应付合同所关联的相关信息在审批单中，不用手动去填写

### Steps To Reproduce 重现步骤

操作步骤：
应付-》应付合同-》新建-》发起审批

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/f1d283eb-5c8f-4fbf-962f-3e053f0b59f3)

### Version 版本

2.6.3

**Comment by marchtian** [comment]
https://github.com/steedos-labs/feikongwang/issues/75

**Comment by marchtian** [comment]
并入 #75
