### ISSUE TITLE
【付款单】付款单台账界面默认没有“合同名称”栏显示，不容易看出所付款项是哪个合同的

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#124]
### Description

测试问题：
付款单台账界面默认没有“合同名称”栏显示，不容易看出所付款项是哪个合同的

预期结果：
建议增加“  合同名称  ”栏

### Steps To Reproduce 重现步骤

操作步骤：
应付-》付款单
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/42b41c80-6de2-4292-863c-298ac057034c)

### Version 版本

2.6.3

**Comment by marchtian** [comment]
按目前的设计思路（参考ZKGJ），付款单并不关联合同、付款明细才关联合同
