### ISSUE TITLE
【应付看板】应付报表中的金额有误

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#125]
### Description

测试问题：
应付看板中的金额有误

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/6af48d69-2680-4e6c-ab0b-3990d28ff654)

### Version 版本

2.6.3

**Comment by marchtian** [comment]
计划金额，需调整、已调整。
计划付款金额，待增加过滤机制

**Comment by marchtian** [comment]
https://github.com/steedos-labs/feikongwang/issues/128
