### ISSUE TITLE
【应付看板】 应付看板中的应付账款TOP5 数据无排序

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#126]
### Description

测试问题：
应付看板中的应付账款TOP5 数据无排序

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/618a59cf-b6d9-44c7-bb3d-4d04ded2c4d7)

### Version 版本

2.6.3

**Comment by lizheng-steedos** [comment]
关联任务：
- https://github.com/steedos/steedos-platform/issues/6295
