### ISSUE TITLE
【应付看板】应付看板中的金额与下面的名称隔距离太近了

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#127]
### Description

测试问题：
应付看板中的金额与下面的名称隔距离太近了

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/6c458705-9239-45d2-9500-8df6453cec86)

### Version 版本

2.6.3

**Comment by lizheng-steedos** [comment]
看板标准功能，暂时无法调整
