### ISSUE TITLE
[开票记录]: 销售合同总金额不会在开票记录台账中显示，并且开票状态也无法编辑

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#133]
### Description

测试问题：
销售合同总金额不会在开票记录台账中显示，并且开票状态也无法编辑

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/b3d1e30f-7165-4481-a08e-a38b3462944b)

### Version 版本

 2.6.4-beta.4

**Comment by lizheng-steedos** [comment]
这部分逻辑统一处理中，调整后再做测试
