### ISSUE TITLE
[销售合同]: 销售合同中添加产品后保存时报错

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#134]
### Description

测试问题：
销售合同中添加产品后保存时报错

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/1ea94559-dbe2-4df7-ae43-07fe9a3b9148)

### Version 版本

 2.6.4-beta.4

**Comment by lizheng-steedos** [comment]
功能调整中，调整后再做测试
