### ISSUE TITLE
[发票看板]: 自动识别的发票费用类别为空，导致发票报表中数据名称为空

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#136]
### Description

测试问题：
自动识别的发票费用类别为空，导致发票看板中数据名称为空

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/3d134dba-2b1c-4e54-b014-26d7d14297bb)
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/2caaf20a-4928-40d0-97c4-f002f2c599b5)

### Version 版本

 2.6.4-beta.4

**Comment by lizheng-steedos** [comment]
调整发票基础数据中记录的费用类别都有值
