### ISSUE TITLE
【设置模块】逻辑错误，导致无法在设置模块中创建公司的组织架构

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#14]
逻辑错误：

1. 部门大于分部  -- 应该是分部下面可以建不同的部门
2. 在设置模块中新建各部门时必须选择“上级部门”，而上级部门无法新建保存，导致无法创建公司的组织架构

**Comment by hotlong** [comment]
https://github.com/steedos/steedos-platform/issues/6115
