### ISSUE TITLE
【报销单】报销单金额不填写也能发起报销流程审批

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#140]
### Description

测试问题：
报销单金额不填写也能发起报销流程审批

建议修改：
发起报销流程时金额改为必填项

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/6c05c31f-ed63-4deb-aaca-dfe9332a89f4)

### Version 版本

2.6.4-beta.4

**Comment by lizheng-steedos** [comment]
明细表必填功能，平台层面调整
