### ISSUE TITLE
[审批]: 应付、报销、应收模块无法发起审批

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#148]
### Description

测试问题：
无法发起审批

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/69684e1e-56f5-448f-9d2f-7f090dee8ca5)

### Version 版本

2.6.4-beta.10

**Comment by lizheng-steedos** [comment]
- 报销应用下审批是好的
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/dd91cd90-7b31-4470-8fc6-a70f53052a1f">

**Comment by lizheng-steedos** [comment]
- 应付流程已调整
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/a6d33b06-e60d-4460-b0fc-933d29bb1ba1">

**Comment by lizheng-steedos** [comment]
- 应收流程已调整
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/3879c6fc-82b3-46ce-89f9-29d6d2474318">
