### ISSUE TITLE
[应付]: 应付合同中，付款计划申请单审批状态和单据编号不显示

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#149]
### Description

测试问题：
应付合同中，付款计划申请单审批状态和单据编号不显示

### Steps To Reproduce 重现步骤

操作步骤：
应付-》应付合同-》合同付款
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/f067388b-fb5e-446c-aea4-2acdcb9cca76)

### Version 版本

 2.6.4-beta.10

**Comment by lizheng-steedos** [comment]
审批单状态好了；单据编号隐藏
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/7104de5a-9e3f-4dd8-b388-c73385be1fa4">
