### ISSUE TITLE
[附件]: 附件详情中有描述栏，实际无法编辑

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#150]
### Description

测试问题：
付款单的附件详细中有描述栏，实际无法编辑

### Steps To Reproduce 重现步骤

操作步骤：
应付-》付款单-》附件-》详细

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/740807b0-c3d2-4d13-b01c-8d862bd770d3)

### Version 版本

2.6.4-beta.10

**Comment by lizheng-steedos** [comment]
平台调整：
- https://github.com/steedos/steedos-platform/issues/6277
