### ISSUE TITLE
【费用类别】 费用类别中缺少“住宿费”，出差报销时会用到，建议加入

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#151]
### Description

测试问题：
费用类别中缺少“住宿费”

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/8eb00c7c-74fc-4091-902e-b51f8152059d)

### Version 版本

 2.6.4-beta.10

**Comment by lizheng-steedos** [comment]
基础数据已添加
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/ef320b82-d2a6-4983-8168-2a59c30ddc05">
