### ISSUE TITLE
【客商】客商的其他信息中提示错误

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#152]
### Description

测试问题：
客商的其他信息中提示错误

### Steps To Reproduce 重现步骤

操作步骤：
客商-》选择任意条客商记录进入-》其他
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/ab06782f-a731-4817-a487-455b2bbf2fb5)

### Version 版本

 2.6.4-beta.10

**Comment by lizheng-steedos** [comment]
已修正
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/681897cf-d07f-4a75-a18e-773add3a9fed">
