### ISSUE TITLE
【应收合同】在应收台账点击应收合同，报错

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#154]
### Description

测试问题：
在应收台账点击应收合同，报错

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/ff94536f-fe6a-42b3-9b6d-02642d797105)

### Version 版本

 2.6.4-beta.10

**Comment by chenzhipei** [comment]
新建合同台账，发起审批后同步台账，合同标签的值为空字符串，而台账中的合同标签字段为多选
![image](https://github.com/steedos-labs/feikongwang/assets/15027092/8e659465-e615-4416-9b2c-d9f52cb9ead1)

已有相关issue: https://github.com/steedos/steedos-platform/issues/5854
