### ISSUE TITLE
[Bug]: 【开票】对象记录审批完成后审批状态一直是进行中，并且服务端有报错

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos-labs/feikongwang#159]
### Description

<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/7211e510-09ed-47c7-90e3-6c7da4d286ec">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.6.4-beta.13

**Comment by ysc1234** [comment]
关联任务：
 - https://github.com/steedos/steedos-platform/issues/6317
