### ISSUE TITLE
【借款】新建借款可以挂上已经结束的报销单

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#178]
### Description

测试问题：
可以挂上已经结束的报销单

### Steps To Reproduce 重现步骤

测试前提：
存在某个报销单已经审批结束，比如年会报销

测试步骤：
报销-》借款-》新建-》编辑时选择已经结束的年会报销单-》确定-》发起审批-》审批结束

### Version 版本

2.6.6-beta.9

**Comment by lizheng-steedos** [comment]
借款只能选择没用发起审批流程的报销台账记录（审批状态为空）
