### ISSUE TITLE
【报销】差旅申请单审批通过后新建的报销单未发起审批，审批状态也会显示已审核

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#179]
### Description

测试问题：
差旅申请单审批通过后新建的报销单未发起审批，审批状态也会变为已审核

### Steps To Reproduce 重现步骤

操作步骤：
报销-》差旅申请-》新建-》发起审批-》审批结束-》点击进入该差旅申请-》报销单-》新建-》保存
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/bf13fe7e-62f2-4d8e-b76b-de1b7caa99ea)

### Version 版本

2.6.6-beta.9

**Comment by lizheng-steedos** [comment]
报销是关联到差旅对象的，所以审批状态是单独的，不和差旅的审批有关系。
后续应该禁止子表编辑开关打开。
