### ISSUE TITLE
【应付合同】无法自动匹配到前面新建合同时所对应的供应商数据，不方便使用

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#18]
操作步骤：
应付合同-》新建-》保存-》相关-》收款方

测试问题：
无法自动匹配到前面新建合同时所对应的供应商数据，不方便使用

**Comment by ysc1234** [comment]
- [x] 在付款列表上，选择应付合同，现在能带出收款方
- [x] 在应付合同相关里，创建付款，目前还无法带出收款方
