### ISSUE TITLE
切换工作区时看到很多个重复的工作区，进入设置界面报错

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#187]
### Description

测试问题：
切换工作区时看到很多个重复的工作区，进入设置界面报错

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/13645ae0-f7a2-43e7-b810-25f1f3ab68ea)

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/9c023e77-3d44-4fa5-96e7-b90861bde6f5)

### Version 版本

 2.6.7

**Comment by lizheng-steedos** [comment]
最新版本暂未重现
