### ISSUE TITLE
[Bug]: 统计分析中仪表盘页面问题偶发性显示不出来

### ISSUE THREAD

**Issue by marchtian** [steedos-labs/feikongwang#24]
### Description

https://github.com/steedos/steedos-platform/issues/6068

报错原因是报表中依赖了expense_advance_payment 对象的 count字段. 但是对象定义上找不到.

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/7553007/ebd68371-1c8f-407b-af1c-9bb4c0f06d3f)

### Version 版本

2.6.2-beta.24

**Comment by lizheng-steedos** [comment]
平台修改，待新版本发布
