### ISSUE TITLE
【发票】: 发票编辑界面自带“差旅 ”字符，无实际作用

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#27]
### Description

测试问题：
发票编辑界面自带“差旅 ”字符，无实际作用也无法去除
预期结果：
去掉

### Steps To Reproduce 重现步骤

应付-》发票-》选择任意发票右边倒三角-》编辑
![企业微信截图_17043615535505](https://github.com/steedos-labs/feikongwang/assets/92509428/3aa76384-fa0a-4dfd-aba9-51d9e788a352)

### Version 版本

2.6.2-beta.28

**Comment by ysc1234** [comment]
这是因为该字段配了readonly属性，所以编辑页无法编辑，可以在编辑状态隐藏该字段。visible_on: "{{global.mode ==='read'}}"
需确认是否隐藏
不止这个字段，invalid_sign（是否作废）红冲也是。
