### ISSUE TITLE
[Feature]: 发票对象表单样式优化

### ISSUE THREAD

**Issue by hotlong** [steedos-labs/feikongwang#32]
### Summary 摘要

<img width="1301" alt="企业微信截图_3d8c051c-5dc1-44ad-9400-5f9bec89bd61" src="https://github.com/steedos-labs/feikongwang/assets/50353452/cf5f3c70-fcbe-474f-b009-28942e047e2a">

### Why should this be worked on? 此需求的应用场景？

业务

**Comment by tujiajun** [comment]
目前只能做到样式上的修改，需要等待附件预览组件的完成，再实现附件预览
