### ISSUE TITLE
[Bug]: 发票识别导入的数据类别字段无法带出

### ISSUE THREAD

**Issue by ysc1234** [steedos-labs/feikongwang#33]
### Description

<img width="1430" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/129827462/bbea63af-c25a-448b-93be-3278cd51c0ca">

### Steps To Reproduce 重现步骤

如图

### Version 版本

 2.6.2-beta.30

**Comment by lizheng-steedos** [comment]
相关任务：
- https://github.com/steedos-labs/feikongwang/issues/45
