### ISSUE TITLE
【预付款】预付款中只有金额，缺少供应商及相关联合同信息，不方便查找

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#41]
### Description

测试问题：
预付款中只有金额，缺少供应商及相关联合同信息，不方便查找

预期结果：
建议参考账款管家，将供应商、待核销合同等相关信息加到台账的标题中

### Steps To Reproduce 重现步骤

操作步骤：
应付合同-》预付款

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/5b08fa67-423b-4a2c-b6d9-3a2c02d3b985)

账款管家参考：
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/0e2e6897-9a8c-40c2-9925-8b3a6936ec9c)

### Version 版本

2.6.2-beta.30

**Comment by hotlong** [comment]
https://github.com/steedos-labs/feikongwang/issues/22
