### ISSUE TITLE
【基础数据】费用类别不正确，参考账款管家修改

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#45]
### Description

测试问题：
费用类别不正确

期望结果：
参考账款管家修改

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/89d0df3b-5af6-4eaa-9a76-0033976a74f4)

账款管家如下：
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/38f85cde-4757-435f-abdf-3b15532003b3)

### Steps To Reproduce 重现步骤

操作步骤：
基础数据-》费用类别

### Version 版本

2.6.2-beta.30

**Comment by lizheng-steedos** [comment]
按照账款管家调整费用类别基础数据
