### ISSUE TITLE
报销单对象业务逻辑

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos-labs/feikongwang#5]
- “差旅”字段：
    - [x] 新建记录时，“差旅”字段只可以选择“已审批”状态的差旅记录；
  
- 报销详情页“发票”子表：
    - [x] 增加“关联费用发票”按钮；（只在记录详情页显示）
    - [x] 点击按钮后，显示状态为“未关联报销”的“费用”对象列表页；
    - [x] 勾选单/多条记录后，将“费用”对象对应记录的“报销”字段更新为当前“费用”对象记录；
    - [x] 同时，参照（https://github.com/steedos-labs/expense/issues/3 ）任务逻辑，更新“费用”对象的“状态”、“报销”、“差旅”字段；
  
- 报销详情页“借款”子表：
    - [x] 增加“关联借款”按钮；（只在记录详情页显示）
    - [x] 点击按钮后，显示（（”报销“或“差旅”字段为空的数据）或（和主表差旅字段和借款差旅字段一致并且借款中报销字段为空））并且借款审批通过的记录；
    - [x] 勾选单/多条记录后，将“报销”对象对应记录的“报销”字段更新为当前“借款”对象记录
    - [x] 报销单如果报销关联了差旅，则同时应该更新借款单中的“应用到差旅”；

**Comment by ysc1234** [comment]
报销单没有差旅字段
