### ISSUE TITLE
【应收合同】新建应收合同时选择客户名称后，选择联系人应该匹配到该客户的联系人

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#58]
### Description

测试问题：
新建应收合同时选择客户名称后联系人不会匹配到该客户所关联的联系人

对比账款管家：
当客户名称确定以后，联系人可选择该客户所关系的人员
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/7469d189-c46d-4602-ac6c-9dad7610f24b)

### Steps To Reproduce 重现步骤

操作步骤：
应收-》应收合同-》新建-》选择客户

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/ea84df4d-d12f-4850-8ae9-79e3cf01787f)

### Version 版本

 2.6.2-beta.30

**Comment by ysc1234** [comment]
客商负责人作为应付合同的联系人
![image](https://github.com/steedos-labs/feikongwang/assets/129827462/46d674c9-24a4-43ed-a89b-8291540fd5b6)
![image](https://github.com/steedos-labs/feikongwang/assets/129827462/00b00132-19eb-41fb-b26d-85d1c6c326c2)
