### ISSUE TITLE
【报销单】报销单费用字段改为发票数

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#60]
### Description

测试问题：
报销单明细中的费用名称目前显示数字，容易误解成费用的金额

预期结果：
建议参照账款管家，改为自动生成的编号，如下图所示：
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/315de671-7e92-4b90-b27a-936b9b484ced)

### Steps To Reproduce 重现步骤

操作步骤：
报销-》报销单-》点击任意条记录进入-》详细

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/2b5577c2-322b-40c8-8b1d-01cfc5fb8ea0)
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/a0e6b704-aa19-4cf5-953f-9949ece61835)

### Version 版本

2.6.2-beta.30

**Comment by hotlong** [comment]
字段名改为发票数，费用都改为发票
