### ISSUE TITLE
[Task]: 开新环境，确认每一条demo数据是否正常

### ISSUE THREAD

**Issue by hotlong** [steedos-labs/feikongwang#66]

**Comment by hotlong** [comment]
相关： https://github.com/steedos-labs/feikongwang/issues/57

**Comment by wangyanwa** [comment]
1. 联系人乱码  --  新环境验证已经OK
2. 报销-》差旅申请-》报销-》报销单-》新建，差旅显示乱码
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/c386b884-ddfe-4b99-82a1-ad1426f605a0)
3. 报销-》差旅申请-》借款-》新建，应用到差旅显示乱码
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/a3c2c2b3-9c2e-44fe-a8f0-07ed57d3483c)
4.应付-》付款单-》新建-》供应商收款账户显示乱码
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/3460ae34-7a34-40f6-bb12-b10744d393c4)

**Comment by wangyanwa** [comment]
5. 应收-》收款-》银行账号，业务伙伴显示乱码
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/f3ffde35-10d1-4292-8956-0da4d6c1828e)

**Comment by ysc1234** [comment]
4、5初始化数据好了，
2、3是因为有过滤规则，所以显示id
需特殊处理，若审批状态不为已核准，则隐藏报销单、借款

**Comment by lizheng-steedos** [comment]
- [ ] 发票对象需要更新数据，新增发票编号字段（费用类别字段要有值，否则看板看起来不好看）

<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/5e7cb21c-0af0-41f3-a75e-388f5bee38c7">

**Comment by lizheng-steedos** [comment]
- [ ]  #78
![image](https://github.com/steedos-labs/feikongwang/assets/151509384/287ff95d-6dc4-40d3-9231-888e4a4dc344)

**Comment by lizheng-steedos** [comment]
- [ ] 客商的数据看起来也不好看
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/003ab98e-9f65-469f-bee3-6cfbffd4a8d8">

**Comment by wangyanwa** [comment]
2.6.3 版本验证结果如下：

2、报销-》差旅申请-》报销-》报销单-》新建，差旅显示乱码   --仍存在  BUG #46 继续跟踪
3、报销-》差旅申请-》借款-》新建，应用到差旅显示乱码   --已OK
4、应付-》付款单-》新建-》供应商收款账户显示乱码    --已OK
5、应收-》收款-》银行账号，业务伙伴显示乱码   --已OK
6、发票对象需要更新数据，新增发票编号字段（费用类别字段要有值，否则看板看起来不好看）  --已OK

问题先关闭
