### ISSUE TITLE
[Bug]: gitpod平台上，重启platform+feikongwang2个服务后，原录入数据会被清除

### ISSUE THREAD

**Issue by marchtian** [steedos-labs/feikongwang#80]
### Description

重启2个服务后，原录入数据会被清除，只剩余系统初始化的数据
如果只重启feikongwang服务，原有数据正常

### Steps To Reproduce 重现步骤

重启platform+feikongwang2个服务后，观察原有录入的数据

### Version 版本

2.6.2-beta.35

**Comment by marchtian** [comment]
以下数据没有了：付款单 等
但其他对象数据仍在

**Comment by chenzhipei** [comment]
本地未还原
