### ISSUE TITLE
【应付合同】合同详细中关于金额的显示数据不完整，建议修改

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#81]
### Description

测试问题：
合同详细中关于金额的显示数据不完整，建议修改

预期结果：
1. 缺少合同金额   --即合同的总金额
2. 缺少核销金额、折让金额     -- 借款及折扣金额实际会发生，系统中未能体现

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/85b0dffe-9e58-46ea-b175-26fe0f1677db)

### Version 版本

2.6.2-beta.35

**Comment by marchtian** [comment]
https://github.com/steedos-labs/feikongwang/issues/22
