### ISSUE TITLE
【客商】应付或应收合同的客商台账界面，对象的宽度无法调节，目前不美观

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#82]
### Description

测试问题：
应付或应收合同的客商台账界面，对象的宽度无法调节，目前不美观

预期结果：
建议修改为可自行拖拉进行调节

### Steps To Reproduce 重现步骤

操作步骤：
应收或应付合同-》客商

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/7b9f19ca-4f40-49af-9262-b4b8de497b29)

### Version 版本

2.6.2-beta.35

**Comment by lizheng-steedos** [comment]
平台问题，关联任务：
- https://github.com/steedos/steedos-platform/issues/6197
