### ISSUE TITLE
【发票】所有发票详细中都有“差旅”，没有实际意义，建议去掉

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#83]
### Description

测试问题：
所有发票详细中都有“差旅”，没有实际意义，建议去掉

### Steps To Reproduce 重现步骤

操作步骤：
应收或应付-》发票-》选择任意发票-》详细
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/15c9a492-4d89-4d48-b607-ffbf8b9c51ca)

### Version 版本

2.6.2-beta.35

**Comment by lizheng-steedos** [comment]
同时修改报销中添加发票后自动带出差旅字段的相关开发
