### ISSUE TITLE
【付款单】应付合同中新建付款单时，选择了付款合同后无法关联上所对应的发票

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#84]
### Description

测试问题：
应付合同中新建付款单时，选择了付款合同后无法关联上所对应的发票，在所有的发票池中选择很不方便

### Steps To Reproduce 重现步骤

操作步骤：
应付-》付款单-》付款记录-》新建
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/13abd59b-94dd-44d1-8477-979f676bdfc5)

### Version 版本

2.6.2-beta.35

**Comment by marchtian** [comment]
已改方案，发票不关联付款明细/ 付款记录
