### ISSUE TITLE
【审批单】合同发起审批时的付款金额、应付金额、发票金额格式显示错误

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#85]
### Description

测试问题：
合同发起审批时的付款金额、应付金额、发票金额格式显示错误，目前显示百分比

预期结果：
显示正常的金额数值

### Steps To Reproduce 重现步骤

操作步骤：
应付-》应付合同-》选择某条合同记录-》发起审批单

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/3ef30020-d9bf-4ddd-b49e-a568f2ec73bd)

### Version 版本

2.6.2-beta.35

**Comment by lizheng-steedos** [comment]
平台bug：
- https://github.com/steedos/steedos-platform/issues/6161
