### ISSUE TITLE
【审批】: 合同或报销审批界面添加关联文件时可选择的不全

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#86]
### Description

测试问题：
合同审批界面添加台账时可选择的关联文件不全。目前只能显示1条记录，合同所关联的台账找不到

预期结果：
应显示合同所关联的文件信息完整

### Steps To Reproduce 重现步骤

操作步骤：
应付合同-》选择任意条合同-》点击右上角“发起审批”-》点击“关联文件”
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/405f68a5-434f-4ae8-8eb9-2849a8265209)

### Version 版本

2.6.2-beta.35

**Comment by lizheng-steedos** [comment]
审批王端禁止修改和发起审批流程
