### ISSUE TITLE
【产品分组】应收合同新建产品分组明细时报错

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#88]
### Description

测试问题：
应收合同新建产品分组明细时报错

预期结果：
无报错信息，正常新建

### Steps To Reproduce 重现步骤

操作步骤：
应收合同-》相关-》产品-》新建-》产品分组-》新建-》上级产品分组-》新建-》保存-》返回上一层，点保存-》保存
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/be6b1a57-fb54-4b7f-ad82-0637f9f0917e)

### Version 版本

2.6.2-beta.35

**Comment by lizheng-steedos** [comment]
平台bug：
- https://github.com/steedos/steedos-platform/issues/6106
