### ISSUE TITLE
【审批】：出差申请提交审批后界面显示错误

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#90]
### Description

测试问题：
出差申请提交审批后界面显示错误

预期结果：
正常显示上方信息

### Steps To Reproduce 重现步骤

操作步骤：
报销-》差旅报销-》新建-》提交审批

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/2885c569-b586-4449-8061-6072644a6d49)

### Version 版本

2.6.2-beta.36

**Comment by lizheng-steedos** [comment]
同问题： #91
