### ISSUE TITLE
【报销申请】提交的差旅申请审批流程，下一个审批人收不到待审批的单

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#91]
### Description

测试问题：
提交的差旅申请审批流程，下一个审批人收不到待审批的单

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/a567cc7d-bee8-4336-9e4c-9f5dfec4f31b)

### Version 版本

2.6.2-beta.36

**Comment by lizheng-steedos** [comment]
因为流程分类没有绑定对应应用，导致找不到审批的单据
