### ISSUE TITLE
【客商】客商无法发起审批

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#93]
### Description

测试问题：
客商无法发起审批

### Steps To Reproduce 重现步骤

操作步骤：
基础数据-》客商-》新建-》编辑完相关信息-》发起审批
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/a5e461f5-60aa-4bf8-aed9-41fd9961b935)

### Version 版本

2.6.2-beta.36

**Comment by ysc1234** [comment]
客商审批流程已去掉
