### ISSUE TITLE
【付款计划】在台账列表界面可以编辑付款说明，但无法提交保存

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#97]
### Description

测试问题：
在台账列表界面可以编辑付款说明，但无法提交保存

### Steps To Reproduce 重现步骤

操作说明：
应付-》应付合同-》点击某个合同进入-》相关-》付款计划-》在列表中直接编辑付款说明-》点击“确认”
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/e2884957-60c9-405a-8700-5e9bbbc7b12a)

### Version 版本

2.6.3

**Comment by lizheng-steedos** [comment]
平台问题：
- https://github.com/steedos/steedos-platform/issues/6196
