### ISSUE TITLE
【关联发票】 在应付合同中关联发票会报错

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#98]
### Description

测试问题：
在应付合同中关联发票会报错

### Steps To Reproduce 重现步骤

操作步骤：
应付-》应付合同-》相关-》发票-》点击“关联发票”-》选择发票-》确定
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/daaa6078-649d-4f8f-8a09-e3e38629ab27)

### Version 版本

2.6.3

**Comment by wangyanwa** [comment]
在上面的操作后继续点击“关联发票”，之前的发票会消失
![image](https://github.com/steedos-labs/feikongwang/assets/92509428/4eb0c1bf-9fc8-45ef-8034-79adf72382c6)

**Comment by lizheng-steedos** [comment]
应付中也添加相应关联发票功能，先整理好相关开发逻辑，确认好再开发
