### ISSUE TITLE
【审批】: 应付合同中新建审批，已勾选对应的合同后合同金额和合同编号不会自动带出也无法编辑

### ISSUE THREAD

**Issue by wangyanwa** [steedos-labs/feikongwang#99]
### Description

测试问题：
应付合同中新建审批，已勾选对应的合同后合同金额和合同编号不会自动带出也无法编辑，导致审批单无法提交

### Steps To Reproduce 重现步骤

 操作步骤：
应付-》审批-》新建-》勾选合同、供应商等关键信息-》编辑合同金额

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/7ff3ced3-5cba-4054-97bb-34b1d0e73928)

### Version 版本

2.6.3

**Comment by marchtian** [comment]
应付合同审批流程是错的，需重做
https://github.com/steedos-labs/feikongwang/issues/75
